- hosts: localhost
  vars:
    source_key: "./keys/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include: tasks/core.yml
    - include: tasks/ssh.yml
    - include: tasks/git.yml
