# tested and working
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

# working, also decrypts
- name: Install private ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

# works, also decrypts
- name: Install public ssh key
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

# works
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}/.ssh/id_rsa.pub"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
